django_social/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views #import login/logout views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'register/$', views.Register.as_view(), name='register'),
]

django_social/django_social/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^after_login/$', views.AfterLoginPage.as_view(), name='after_login'),
    url(r'^after_logout/$', views.AfterLogoutPage.as_view(), name='after_logout'),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
]

django_social/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name="all"),
    url(r'new/$', views.CreatePost.as_view(), name="create"),
    url(r'by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name="for_user"),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name="single"),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name="delete"),
]

django_social/templates/after_login.html
{% extends "base.html" %}

{% block content %}

<h1>Użytkowniku, witaj na portalu!</h1>

{% endblock %}

django_social/templates/after_logout.html
{% extends "base.html" %}

{% block content %}

<h1>Użytkowniku, dziękujemy za skorzystanie z naszego portalu!</h1>

{% endblock %}

django_social/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>DjangoSocial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {# custom css #}
    <link rel="stylesheet" href="{% static 'django_social/css/main.css' %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js">

    </script>
  </head>
  <body>

    <nav class='navbar main_nav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand main_nav' href="{% url 'home' %}"> Strona główna</a>
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}"> Posty</a></li>
            <li><a href="{% url 'groups:all' %}"> Grupy</a></li>
            <li><a href="{% url 'groups:create' %}"> Utwórz grupę</a></li>
            <li><a href="{% url 'accounts:logout' %}"> Wyloguj</a></li>
          {% else %}
            <li><a href="{% url 'groups:all' %}"> Grupy</a></li>
            <li><a href="{% url 'accounts:login' %}"> Logowanie</a></li>
            <li><a href="{% url 'accounts:register' %}"> Rejestracja</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container main_container">
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

django_social/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Witaj na stronie projektu Django Social!</h1>
{% endblock %}